// ==========================================
// websiteModel.js
// Handles all SQL queries for the websites table
// ==========================================

const db = require("../config/database");

const WebsiteModel = {
  // ==========================================
  // GET ALL WEBSITES
  // ==========================================
  async getAllWebsites() {
    const [rows] = await db.query(
      "SELECT * FROM websites ORDER BY created_at DESC",
    );
    return rows;
  },

  // ==========================================
  // GET WEBSITE BY ID
  // ==========================================
  async getWebsiteById(id) {
    const [rows] = await db.query("SELECT * FROM websites WHERE id = ?", [id]);
    return rows[0]; // Return the first object in the array
  },

  // ==========================================
  // CREATE NEW WEBSITE
  // ==========================================
  async createWebsite(websiteData) {
    const {
      name,
      url,
      crawler_type,
      title_selector,
      link_selector,
      description_selector,
      image_selector,
      author_selector,
      date_selector,
    } = websiteData;

    const [result] = await db.query(
      `INSERT INTO websites 
            (name, url, crawler_type, title_selector, link_selector, description_selector, image_selector, author_selector, date_selector) 
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        name,
        url,
        crawler_type,
        title_selector,
        link_selector,
        description_selector,
        image_selector,
        author_selector,
        date_selector,
      ],
    );

    return result.insertId; // Returns the new ID generated by MySQL
  },

  // ==========================================
  // UPDATE WEBSITE
  // ==========================================
  async updateWebsite(id, websiteData) {
    const {
      name,
      url,
      crawler_type,
      title_selector,
      link_selector,
      description_selector,
      image_selector,
      author_selector,
      date_selector,
      active,
    } = websiteData;

    const [result] = await db.query(
      `UPDATE websites SET 
            name = ?, url = ?, crawler_type = ?, title_selector = ?, link_selector = ?, 
            description_selector = ?, image_selector = ?, author_selector = ?, date_selector = ?, active = ?, updated_at = CURRENT_TIMESTAMP 
            WHERE id = ?`,
      [
        name,
        url,
        crawler_type,
        title_selector,
        link_selector,
        description_selector,
        image_selector,
        author_selector,
        date_selector,
        active,
        id,
      ],
    );

    return result.affectedRows; // Returns 1 if updated, 0 if not found
  },

  // ==========================================
  // DELETE WEBSITE
  // ==========================================
  async deleteWebsite(id) {
    const [result] = await db.query("DELETE FROM websites WHERE id = ?", [id]);
    return result.affectedRows;
  },
};

module.exports = WebsiteModel;
